### ISSUE TITLE
Flashing Arduino Uno and Nano ok, but no success with mega 

### ISSUE THREAD

**Issue by QuimeraCoding** [jacobrosenthal/js-stk500v1#5]
Hello,

First off all thank's a lot for this great tool, good job.

I'm using it in a Chrome packaged app to flash Arduinos from the browser, and it's working ok with Uno's and Nano's, but with Megas I've not been able to flash them with success.

Maybe I'm missing something, is there anything I should change to use it specifically with Megas?

The hex file works with Platformio (that compiles it) and with Arduino IDE.

Thanks in advance.

**Comment by jacobrosenthal** [comment]
From the readme :)
```
Huge thanks to Pinoccio for their stk500v2 browser implementation (for Arduino Megas, etc) from which I stole whole lines of code. We're working to unify our programmers with some sort of overarching module. For now see js-stk500 to program Arduino Mega and Pinoccio's

https://github.com/Pinoccio/js-stk500
```

**Comment by QuimeraCoding** [comment]
Silly me...  :)

Will try it then, thank you.
